### ISSUE TITLE
Button "refresh" ignores text alignment options

### ISSUE THREAD

**Issue by aaronmw** [fuggfuggfugg/sketch-dynamic-button-3.5#1]
If I use centered text for my button and do the ol' "CMD+J" after changing the text, this plugin redraws my button as though my text had been left-aligned. It'd be awesome if it respected the text's alignment and resized the button relative to the center of my text instead.

**Comment by fuggfuggfugg** [comment]
Not sure I understand. Check this gif. 
![sketch dynamic button](https://cloud.githubusercontent.com/assets/5616123/13370989/b8d5e390-dce8-11e5-9f62-6d1b4eac9bb2.gif)

**Comment by aaronmw** [comment]
Ah, but leave width as "auto" and repeat though. It'll resize to the right, and not from the center.

**Comment by aaronmw** [comment]
![](https://dl.dropboxusercontent.com/u/9258007/sketch-button-bug.gif)

**Comment by samsonkhisty** [comment]
Ahh, thanks for the gif. I'll check it out tonight.

**Comment by fuggfuggfugg** [comment]
Thanks to your suggestion, I think this works better. I've already updated the code. Do Play around and let me know if this satisfies. Simply download and double clicking should replace the existing plugin.

![sketch dynamic button](https://cloud.githubusercontent.com/assets/5616123/13418613/13e8a00c-df45-11e5-9957-f16ec23b773f.gif)

**Comment by aaronmw** [comment]
Ooh, exciting — thank you! I'll give it a whirl!

**Comment by aaronmw** [comment]
Works beautifully — thanks again!

**Comment by samsonkhisty** [comment]
I'm glad. Thanks for your suggestion.

**Comment by fuggfuggfugg** [comment]
I'm glad, Thanks for your suggestion.
