### ISSUE TITLE
Not compatible with sketch 39.1

### ISSUE THREAD

**Issue by arthurhazan** [fuggfuggfugg/sketch-dynamic-button-3.5#10]
@fuggfuggfugg :) I'm sure your already on it !

**Comment by fuggfuggfugg** [comment]
Thanks for reporting. However I cannot replicate. 

![sketch dynamic button](https://cloud.githubusercontent.com/assets/5616123/17101481/ceef4ca0-5242-11e6-910c-b5f8c912bb25.gif)

**Comment by arthurhazan** [comment]
Yep, my bad, It's working just fine! Keep up the good work
