### ISSUE TITLE
Appears to be broken in 39.1 

### ISSUE THREAD

**Issue by jdeheus** [fuggfuggfugg/sketch-dynamic-button-3.5#11]
So this worked great for release 39, however it seems to have stopped working in 39.1. The command still works, however it creates a dynamic group folder but sets the text to 0:0:0:0. The only other plugins I have are Craft and Zeplin, and this still happens even if they are disabled.

**Comment by fuggfuggfugg** [comment]
Thanks for reporting. However I cannot replicate the issue. 

![sketch dynamic button](https://cloud.githubusercontent.com/assets/5616123/17101481/ceef4ca0-5242-11e6-910c-b5f8c912bb25.gif)

**Comment by biron-io** [comment]
> The command still works, however it creates a dynamic group folder but sets the text to 0:0:0:0.

I am having the exact same issues on 39.1 even when I disable all my other plugins.

**Comment by fuggfuggfugg** [comment]
@biron-io Thanks for reporting. If it's not too much trouble, can I request you to reinstall the plugin and see if the issue still exists?

There was a similar issue earlier #10

**Comment by fuggfuggfugg** [comment]
@jdeheus @biron-io  Is this still an issue?

**Comment by biron-io** [comment]
@fuggfuggfugg Sorry for not getting back to you. Reinstalling the plugin fixed it for me, thanks for your help.

**Comment by fuggfuggfugg** [comment]
No worries. Glad it worked. Thanks for actively using the plugin.

**Comment by jdeheus** [comment]
Reinstalling worked for me, sorry for not responding sooner!

**Comment by fuggfuggfugg** [comment]
@jdeheus No worries. Glad it worked.
