### ISSUE TITLE
Changing text wont change button background size

### ISSUE THREAD

**Issue by asrneo** [fuggfuggfugg/sketch-dynamic-button-3.5#12]
I made a button with padding 5:8, duplicated it and changed the text to the normal text for the button, and the background size didn't change. What am I doing wrong?
![screen shot 2016-08-09 at 11 38 30 am](https://cloud.githubusercontent.com/assets/1288973/17522649/cfae868a-5e25-11e6-8081-56e22ef4f4fe.png)

**Comment by fuggfuggfugg** [comment]
@asrneo Sorry you are having trouble. Unfortunately the background won't automatically change after changing the text.  You have to manually do a (Cmd + j) again with the text layer selected. 

I will update the readme for you once I get back home.

![Here is an old gif](https://cloud.githubusercontent.com/assets/5616123/13418613/13e8a00c-df45-11e5-9957-f16ec23b773f.gif)

**Comment by fuggfuggfugg** [comment]
@asrneo Is this still an issue?
