### ISSUE TITLE
Doesn't work with symbols

### ISSUE THREAD

**Issue by aaadryyy** [fuggfuggfugg/sketch-dynamic-button-3.5#13]
Since buttons are used again and again, they'll likely be set as symbols.

Unfortunately the plugin doesn't work with symbols :/ ... yet ?

![](https://media.giphy.com/media/l3vRg4QhrnRdOYTfy/giphy.gif)

**Comment by fuggfuggfugg** [comment]
Sorry for the inconvenience. 

From what I heard, SketchApp is working on it's own button control in one of the upcoming releases after which this plugin may not be necessary. Hence I'm currently simply maintaining it to work with all new versions and not looking into enhancing the plugin.

**Comment by aaadryyy** [comment]
Good to know !

You did a great job ;)

**Comment by fuggfuggfugg** [comment]
[I had logged this request earlier and this is where the dev mentioned a native button is coming up](http://mail.sketchplugins.com/pipermail/dev_sketchplugins.com/2016-June/003851.html) 

Thanks for using the plugin.

**Comment by fuggfuggfugg** [comment]
@aaadryyy 
I have created branch for Dynamic Button to work with Symbols. You can refer to #19 to download a copy and test. Still in beta.
