### ISSUE TITLE
When I update the padding and rebuild the button it creates a new button inside the old one.

### ISSUE THREAD

**Issue by alexandra-aas** [fuggfuggfugg/sketch-dynamic-button-3.5#14]
![issue](https://cloud.githubusercontent.com/assets/1214346/18111187/88227426-6eeb-11e6-976c-b2333183c476.gif)

**Comment by fuggfuggfugg** [comment]
Hi @alexandra-aas, 
After you update the padding, keep the text layer (30:20) selected and then rebuild (Cmd + J). 

Update: I'll add some better error handling in the next update. I noticed the same issue if I rebuild with the BG layer selected. 

Thanks for reporting.

**Comment by fuggfuggfugg** [comment]
Hi @alexandra-aas , Just following up to see if your issue is fixed. Also I have updated the plugin for some better error handling. You can view a demo here. 

![sketch dynamic button](https://cloud.githubusercontent.com/assets/5616123/18656128/94614d62-7ebc-11e6-870e-5314fa1bd2ec.gif)

Please let me know if the issue still occurs and I can assist you.

**Comment by freefood89** [comment]
(v41.2)

I have the same issue. Even worse, when I select the text layer and cmd+J it resets the name of the text layer to "20:20"

If I select box the button and the text layer as you've done in the gif, it creates another button around that button

**Comment by fuggfuggfugg** [comment]
> I have the same issue. Even worse, when I select the text layer and cmd+J it resets the name of the text layer to "20:20"

My apologies. I just fixed the issue. Can you please re-install the plugin and try again. If you don't set any padding in the text layer name then it will apply 20:20 as default padding. 

> If I select box the button and the text layer as you've done in the gif, it creates another button around that button

You need to select the text layer only at all times to add the padding again. I had recently added logic to ignore any other selection to address this issue but I received some complaints and had to revert it back.


Let me know if you still encounter issues, I will do my best to assist. Sorry again for the inconvenience and thanks for reporting the issue.

**Comment by freefood89** [comment]
@fuggfuggfugg fixed thanks 👍

**Comment by fuggfuggfugg** [comment]
Glad it worked. Thanks for reporting the issue.
