### ISSUE TITLE
Button resizing (apple+J) stopped working

### ISSUE THREAD

**Issue by prefontaine** [fuggfuggfugg/sketch-dynamic-button-3.5#15]
Love this plugin. Sadly, today it has stopped resizing. Tried un- and re-installing. OSX 10.11.6. Tried Sketch v39 and v39.1.

**Comment by fuggfuggfugg** [comment]
Hi @prefontaine, 
My apologies, Let me poke around it tonight after I get home. I'll update soon.

**Comment by prefontaine** [comment]
Awwwww. No problem. Just wanted to let you know. Thank you for getting back
to me so quickly!

**Comment by fuggfuggfugg** [comment]
@prefontaine Thanks for your patience.

I'm on Mac 10.10.5 and I failed to reproduce an issue. I also added 2 new features and updated the plugin.  Can I request you to try this new plugin and see if the issue still occurs. 

As for the new features, 
- Now you can add a single value. For eg. If you update the layer name to 15 and run the plugin, it will add 15px padding on all 4 sides. If you do not add any values, it will default to 20px. 
- I also added better error handling, previously the plugin worked on any layers. At times, I selected the BG layer by default and hit Cmd+J and it would create the folders around the layer. This was annoying, now I specifically ignore all other layers so no more mistakes. Even if you select multiple layers, it will only run default button changes to the text layer and ignore all other layers. 

Here's a small demo

![sketch dynamic button](https://cloud.githubusercontent.com/assets/5616123/18656128/94614d62-7ebc-11e6-870e-5314fa1bd2ec.gif)

Thanks again for reporting the issue. Please let me know if the issue still arises. I'll proceed to update my mac and try it again.
Cheers.

**Comment by prefontaine** [comment]
Thank you @fuggfuggfugg. I figured out what I was doing wrong. So silly: Somehow the dimensions of the text box had been changed. So it was working — to the text box. Thanks again for the quick response and for updating this awesome plugin. I love it!
