### ISSUE TITLE
'Improvement' of applying to only text layers reduces functionality

### ISSUE THREAD

**Issue by sweetyams** [fuggfuggfugg/sketch-dynamic-button-3.5#17]
The recent switch to only affect text layers us a really big change and affects a lot of cases that we were using the plugin for. We consistently use the plugin to setup margin and padding with groups of elements so for it to only apply to text elements cause a lot of problems.

is it possible to revert this change to allow the plugin to apply to more than just text layers?

**Comment by fuggfuggfugg** [comment]
Also pinging @mikeprecious 

@sweetyams, Apologies mate. I'll revert this tonight. 

If you want to fix this temporarily, Navigate to the plugin folder and open the plugin in any editor.

https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/blob/master/DynamicButton3.5.sketchplugin/Contents/Sketch/script.cocoascript#L98

And you can replace the if condition from 

`if( [currentLayer class] ==  MSTextLayer ){`
to 
`if( 1 == 1 ){`

and save the file. 

This should fix it for now. I'll update the repo tonight.

**Comment by fuggfuggfugg** [comment]
@sweetyams @mikeprecious

I've removed the check and updated. You can download & reinstall the plugin. 

Thanks for the feedback.

**Comment by sweetyams** [comment]
Thanks! this is amazing.

Thank you for jumping on this so quickly
