### ISSUE TITLE
Modify Default Styles

### ISSUE THREAD

**Issue by lanceadam** [fuggfuggfugg/sketch-dynamic-button-3.5#20]
Is there a way to set default styles for my file? i.e, I want to set the background colour of the button container and remove the radius?

**Comment by fuggfuggfugg** [comment]
Sure, I've updated the plugin so it is easy for you to override the defaults.

- Download and Re-Install the plugin. 
- You will need to open the plugin in a Text Editor and update these 3 lines: https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/blob/master/DynamicButton3.5.sketchplugin/Contents/Sketch/script.cocoascript#L13-L15
- Click Gif Below to expand


![override](https://cloud.githubusercontent.com/assets/5616123/21076875/336d7902-bf05-11e6-85e5-d25f7261a228.gif)

If in any case the plugin stops working, re-install again to get the default values.

**Comment by lanceadam** [comment]
Thank you!

How would I go about setting the background to no fill and applying an outline instead?  i.e for “outline/line” style buttons?


Kind Regards
Lance Redgrave | Managing Director


Level 1, 52-54 Willoughby Rd Crows Nest 2065

p(02) 9439 9115 <tel:0294399115> m0405 419 755 <tel:0405419755>
elance@redfoxmedia.com.au <mailto:lance@redfoxmedia.com.au>
www.redfoxmedia.com.au <http://www.redfoxmedia.com.au/> 		 <https://www.google.com/partners/?hl=en-US#a_profile;idtf=8008220449> 		 <http://www.webindustry.asn.au/directory/profile/redfoxmedia/> <http://www.linkedin.com/company/2622382>  <https://www.facebook.com/RedfoxMedia1>  <https://twitter.com/redfoxmedia1>  <https://plus.google.com/+RedfoxMediaAU/>  <http://redfoxmedia.com.au/rss/>

**Comment by fuggfuggfugg** [comment]
[DynamicButton3.5.sketchplugin.zip](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/files/718464/DynamicButton3.5.sketchplugin.zip)

This plugin only for you. Unzip the file and install this plugin. It has no fill and `#828282` as default border.

To edit the border color and thickness: 

1. Open plugin in a text editor (previous gif)
2. Line 17 & 18, Change `borderColor` and `borderThickness` to your liking.

Let me know how it goes.

**Comment by lanceadam** [comment]
Awesome thanks!

Kind Regards
Lance Redgrave | Managing Director


Level 1, 52-54 Willoughby Rd Crows Nest 2065

p(02) 9439 9115 <tel:0294399115> m0405 419 755 <tel:0405419755>
elance@redfoxmedia.com.au <mailto:lance@redfoxmedia.com.au>
www.redfoxmedia.com.au <http://www.redfoxmedia.com.au/> 		 <https://www.google.com/partners/?hl=en-US#a_profile;idtf=8008220449> 		 <http://www.webindustry.asn.au/directory/profile/redfoxmedia/> <http://www.linkedin.com/company/2622382>  <https://www.facebook.com/RedfoxMedia1>  <https://twitter.com/redfoxmedia1>  <https://plus.google.com/+RedfoxMediaAU/>  <http://redfoxmedia.com.au/rss/>
