### ISSUE TITLE
Crashes Sketch if executed with anchor point selected

### ISSUE THREAD

**Issue by derekatkinson** [fuggfuggfugg/sketch-dynamic-button-3.5#21]
Not sure why it happens, but it's easily reproducible. To reproduce: create a vector shape, go into mode for editing paths/anchor points and select an anchor point, and execute the plugin with either the keyboard shortcut or the menu option. Sketch will crash instantly.

I just noticed that this problem also existed in the legacy Dynamic Button plugin, so I'm guessing it's caused by code taken from there.

**Comment by fuggfuggfugg** [comment]
Thanks for reporting, I don't have sketch handy to test it out. Let me get back to you by tonight if possible.

**Comment by derekatkinson** [comment]
Thanks! I'm in no hurry for it to be fixed, since I know what to avoid doing, but thought you might like to know in case you want to make the plugin a bit more stable at some point.

I forgot to mention, I'm using Sketch Version 41.2 (35397).

**Comment by fuggfuggfugg** [comment]
Logged report with Sketch.
