### ISSUE TITLE
Not working with symbols

### ISSUE THREAD

**Issue by cypmal** [fuggfuggfugg/sketch-dynamic-button-3.5#24]
I'm using sketch version 42 (36781) and I have problem with button converted to symbol when I will change text on symbol and  press CMD+J it creating a new dynamic button on the symbol. Please fix it.

**Comment by fuggfuggfugg** [comment]
What do you want it to do instead? 
Currently Dynamic will run on any layer you do cmd+j. 

Also, is this a symbol Master or symbol Instance. If you can make me a gif, I can better understand.

**Comment by brant454** [comment]
@fuggfuggfugg thanks for maintaining this. An added feature, to @cypmal's point, would be to have this capability work on buttons that are converted to symbols. When I place an instance on the artboard and override the label, there's no way to use the dynamic resize.

Is it possible to add this? Thanks in advance.

***update: I just saw that this conversation has been happening in another thread so disregard. I'll keep up over there. Thanks again!

**Comment by fuggfuggfugg** [comment]
@brant454 

Basic symbol overrides are currently working. It resides in a [separate branch](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/tree/sketch-symbols-fuck-yeah). You can use this [download link](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/archive/sketch-symbols-fuck-yeah.zip) to play around.

I am currently still working on supporting nested symbols and it's not as straight forward. Keep an eye on #19 .

Thanks for the feedback and for using the plugin.
