### ISSUE TITLE
Support for added measurements

### ISSUE THREAD

**Issue by jonbraz0** [fuggfuggfugg/sketch-dynamic-button-3.5#25]
![screen shot 2017-04-05 at 5 43 41 pm](https://cloud.githubusercontent.com/assets/26942919/24732719/7556ce9a-1a27-11e7-8daa-ddb17569eb8b.png)
![screen shot 2017-04-05 at 5 43 36 pm](https://cloud.githubusercontent.com/assets/26942919/24732728/7dd8c5e6-1a27-11e7-99ca-a07f60b10644.png)

I thought there was support for this before...but can't seem to get it working.
I would specify an added measurement on the layer above, cmd+j would then space that layer within the button.

**Comment by JWhiteUX** [comment]
Is second this. I could have sworn this was available in an earlier release.

**Comment by fuggfuggfugg** [comment]
It should have worked, can I ask if you are renaming the layer correctly. I see the highlighted layer name is the image you put above is "r:11". can you try by just putting 11 or 11:11. 

My apologies for the delay in replying. Have to work during weekends for a deadline unfortunately.

**Comment by jonbraz0** [comment]
yeah tried 11 and 11:11 and still not working. previously i'd cmd+j the original text used to make the button and it would adjust.

**Comment by JWhiteUX** [comment]
Doesn't work for me either.

I think the point of `R:10` was to align a icon/symbol to the `Right` with 10px padding.

Using `10:10:10:n` would require knowing the left padding, which might change from button to button.

I tried `r:10` `R:10` and 10:10:10:50` and that didn't work either.

**Comment by JWhiteUX** [comment]
Test File
[db3.5-button-and-symbol-padding.zip](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/files/910964/db3.5-button-and-symbol-padding.zip)

**Comment by fuggfuggfugg** [comment]
@jonbraz0, Maybe I'm understanding this incorrectly. If you group the icon and text and apply the 11:11:11:11 to the Group then it will draw the button around it. Is that something you are trying to achieve. 


@JWhiteUX The plugin never supported syntaxes like r:10. Maybe it was a different plugin. 

I'm at work and don't have sketch. I will check the file if I get time in the evening.

**Comment by JWhiteUX** [comment]
Ah… Found it. @jonbraz0 @fuggfuggfugg  — https://evilmartians.com/chronicles/compo-sketch

Compo does the r:10 thing. I would love to have this available in DB3.5. One less plugin to use.

See `Compo Example 3

> Example 3
> 
> Let’s make a more complex control like a drop-down list. Technically, it is just a button with a caret at the right. In the label name, set the right margin big enough for the caret to fit in. Set the caret margin as r:10 — it means it will be 10 pixels from the right edge. Press ⌘J. Now, a drop-down list takes only a few seconds to create.

**Comment by jonbraz0** [comment]
oh man, well that also explains why i thought it worked...same shortcut.
