### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by thelefty** [fuggfuggfugg/sketch-dynamic-button-3.5#26]
Trying to edit the script so that the default has a certain Inner-shadow. Any ideas? Thanks in advance.

**Comment by fuggfuggfugg** [comment]
Sorry for the delay, I was trying this last night but I don't get it to work. The documentation is pretty limited. 

I managed to find a way to assign values if the innershadow already existed but couldn't find a way to add a new instance. I've logged an issue here - http://sketchplugins.com/d/220-adding-new-innershadow-programatically

**Comment by fuggfuggfugg** [comment]
@thelefty Finally someone answered. 

You can add the below code [on this line ](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/blob/master/DynamicButton3.5.sketchplugin/Contents/Sketch/script.cocoascript#L26)

    var innerShadow = container.style().addStylePartOfType(3);
    innerShadow.offsetX = 20.0;
    innerShadow.offsetY = 20.0;
    innerShadow.spread = 3;

I haven't tested this out myself. But try it and let me know if it works. 

Sorry for the delay again.
