### ISSUE TITLE
Changes to group resizing in Sketch 44 affect dynamic buttons

### ISSUE THREAD

**Issue by thunderdunk** [fuggfuggfugg/sketch-dynamic-button-3.5#28]
After updating to Sketch 44 I was having some issues with getting buttons to resize properly. Running the Dynamic Button tool would change the BG layer as expected, but the bounding box for the button group would stay at its original size. Then resizing the group bounding box to fit is a nuisance, and is problematic with the new group resizing options in the Sketch update.

I finally figured out a workaround: run Dynamic Button twice on the text layer. The first time resizes the BG layer, and the second time resizes the group bounding box.

<img width="800" alt="dynbtn1" src="https://cloud.githubusercontent.com/assets/6994924/26461137/f29a9078-4130-11e7-9265-059793877419.png">

<img width="800" alt="dynbtn2" src="https://cloud.githubusercontent.com/assets/6994924/26461136/f29996f0-4130-11e7-8015-676e1aab1eae.png">

<img width="800" alt="dynbtn3" src="https://cloud.githubusercontent.com/assets/6994924/26461135/f298f9ac-4130-11e7-83d8-11294f332435.png">

<img width="800" alt="dynbtn4" src="https://cloud.githubusercontent.com/assets/6994924/26461134/f2977d5c-4130-11e7-8503-f1e763b0941b.png">

@fuggfuggfugg thanks for continuing to work on this plugin, it's a huge timesaver!

**Comment by fuggfuggfugg** [comment]
@thunderdunk Thanks for notifying the issue. Sorry for the delay in responding. I had to renew my license to update the version. Re-install plugin and let me know.

**Comment by thunderdunk** [comment]
@fuggfuggfugg Yay works! Thanks for maintaining this plugin!

**Comment by fuggfuggfugg** [comment]
Not at all. Thanks **YOU** for actively reporting the issue with all details.

Have a nice weekend mate.
