### ISSUE TITLE
Sketch 3.8 bug

### ISSUE THREAD

**Issue by frshnss** [fuggfuggfugg/sketch-dynamic-button-3.5#3]
Version 3.8.1 (29687) has a bug when it comes to generate dynamic button. After CMD+J on the text layer creates an empty folder top of it without the dynamic background.

![screen shot 2016-05-20 at 10 07 53](https://cloud.githubusercontent.com/assets/19482294/15415105/ef2e4fd8-1e72-11e6-92e6-76c5fed817f0.png)

**Comment by fuggfuggfugg** [comment]
Thanks for reporting. Spent 2 hours debugging this. [Found the issue and logged a bug](https://github.com/BohemianCoding/developer.sketchapp.com/issues/51). 

There seems to be an issue in 3.8 for MSStyle File. I'll keep you updated.

**Comment by fuggfuggfugg** [comment]
@frshnss Done Deal! Finally after another 3 hours to tinkering around, It should work. Uninstall the old one and reinstall the new plugin. 

Please test and let me know. Thanks again for using my plugin and also reporting the issue.

**Comment by frshnss** [comment]
Tested and just works perfectly! Thanks much for all of your efforts, this is a incredibly useful plugin.

**Comment by fuggfuggfugg** [comment]
@frshnss No worries at all. Closing the ticket.
