### ISSUE TITLE
Symbols

### ISSUE THREAD

**Issue by mikeprecious** [fuggfuggfugg/sketch-dynamic-button-3.5#32]
@fuggfuggfugg just curious how things are looking with the dev on the Symbols functionality? 

For a prod version, it would be fantastic to see the basic text-in-button format work as a symbol. So each instance of the button I create out on my Page › Artboard with unique text field modifications, I can engage the Cmd+J KB shortcut and the button shape layer base resizes.

**Comment by fuggfuggfugg** [comment]
I'll merge the basic stuff in tonight.

**Comment by fuggfuggfugg** [comment]
Hi @mikeprecious, 

I've merged the "sketch-symbols-fuck-yeah" branch into Master. This supports the basic symbol manipulations. If you have installed Sketchpacks, you should get an option to update the new version. If not, you can reinstall the plugin the old way. 

Let me know how it goes.
