### ISSUE TITLE
Dynamic Button creates unresponsive button in Sketch 45.1

### ISSUE THREAD

**Issue by fbasara-loft48** [fuggfuggfugg/sketch-dynamic-button-3.5#35]
**Steps to reproduce**
- Update Sketch to latest Version and restart
- Select any layer and hit CMD+J
- Try to CMD+Click or simply click the object
- Object can't be selected or moved unless layer which was used to create a Button (e.g Text) is being moved manually with keyboard shortcuts or via the inspector panel.

Video demo
https://gfycat.com/DirtyHeartyBug

**Comment by fuggfuggfugg** [comment]
Thanks for notifying, seems like this new 45.1 update seems to be causing it. I can replicate the issue you mention but I haven't had a chance to debug and verify if it is my plugin or an issue with Sketch itself. I will get back to you again once I have time to dive deeper. 

Thanks again

**Comment by fuggfuggfugg** [comment]
@fbasara-loft48 Issue fixed, Update via Sketchpacks. Let me know how it goes.

**Comment by fbasara-loft48** [comment]
You're a legend @fuggfuggfugg.
Works like a charm!

**Comment by raulfunkie** [comment]
Can confirm it fixes the bug, just had the bug happen to me and the updated successfully fixed it.
