### ISSUE TITLE
Group cannot be selected when created

### ISSUE THREAD

**Issue by gorillabiscuit** [fuggfuggfugg/sketch-dynamic-button-3.5#36]
To replicate this bug (if it is a bug and not some kind of feature that I don't understand) create a new text object. Then hit CMD-J to create a dynamic button. The button cannot be selected. You can see the button in the left column and select either the text layer or the vector object (not the group folder itself)

To make it selectable again, I have to highlight the text object and hit CMD-J again. This then makes it selectable again.

**Comment by fuggfuggfugg** [comment]
Is it same as #35?
https://gfycat.com/DirtyHeartyBug

**Comment by gorillabiscuit** [comment]
Yes, exactly the same problem, I downloaded it today though :/ will try again tomorrow and work and see if it's now fixed.

**Comment by fuggfuggfugg** [comment]
No worries, Let me know how it goes. 

Thanks for actively reporting the issue.

**Comment by fuggfuggfugg** [comment]
@gorillabiscuit Checking in to see if this is working for you.

**Comment by gorillabiscuit** [comment]
Yep, seems to be working correctly now. I've uncovered another issue. Will close this and create a new one.
