### ISSUE TITLE
Dynamic button 3.5 now compatible with SKETCH 3.8.

### ISSUE THREAD

**Issue by fuggfuggfugg** [fuggfuggfugg/sketch-dynamic-button-3.5#4]
Please check out the update gif in the Readme. 

Huge thanks to everyone using this plugin.

**Comment by jasonmoore-wf** [comment]
I installed this latest plugin but it's not creating the background box, or allowing for changes http://recordit.co/yOVjBFMqxq - I did look at the updated GIF as well.

**Comment by fuggfuggfugg** [comment]
hi @jasonmoore-wf 
My apologies, Can I get your Sketch version number. Chances are that the recent Sketch update must have broken the plugin. 

I'm at work currently and cannot look into it right away. I'll make it a point to look at it this evening and fix it for you.

**Comment by jasonmoore-wf** [comment]
Sure thing... it's 
https://www.dropbox.com/s/oqxzzm406klb5nr/Screenshot%202016-07-20%2013.41.01.png?dl=0

I just upgraded today...it wasn't working on v38 either.

**Comment by fuggfuggfugg** [comment]
@jasonmoore-wf 

Plugin should now work with V39. [Click to download Zip ](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/archive/master.zip) and reinstall.

Thanks for using the plugin and reporting on the issue.

**Comment by jasonmoore-wf** [comment]
Love it! It works :) thanks 
https://www.dropbox.com/s/rszrsn6z6dmfk11/Screenshot%202016-07-21%2009.49.35.png?dl=0

**Comment by fuggfuggfugg** [comment]
Glad it worked. Thanks for the confirmation.
