### ISSUE TITLE
Doesn't seem to be working on Sketch 3.8.3

### ISSUE THREAD

**Issue by charlesmudy** [fuggfuggfugg/sketch-dynamic-button-3.5#7]
Any idea why it might not be working on Sketch v3.8.3?

I followed your installation gif, no padding was created with command+J

**Comment by fuggfuggfugg** [comment]
Hi @charlesmudy 

I did a quick test on 3.8.3, works for me. The plugin needs to know the padding ratio in the text layer name for it to apply. What I suspect is when you update the text in the layer for the first time, it overrides the layer name as well. You have to update the layer name again. Unfortunately, that's Sketch behavior and I have no way of overriding it. 

Take a look at this gif. 
![sketch](https://cloud.githubusercontent.com/assets/5616123/16015971/3bd4dc66-3166-11e6-8710-3bd1ad2dc875.gif)

Let me know if you still have an issue.

**Comment by fuggfuggfugg** [comment]
@charlesmudy Any luck?

**Comment by charlesmudy** [comment]
@fuggfuggfugg thanks a lot for the clarification, I just needed to redo click the command+J

**Comment by fuggfuggfugg** [comment]
@charlesmudy That is correct, I also looked into simplifying that as well to see if I can catch a text change event and update the padding but it is not currently supported as far as I know. 

Thanks again

**Comment by charlesmudy** [comment]
@fuggfuggfugg thanks a lot anyways for the help :)

**Comment by aaronmw** [comment]
@fuggfuggfugg event handlers would be a massive game changer for Sketch... I'm surprised they haven't invested in that!

**Comment by fuggfuggfugg** [comment]
The [relabel](https://www.youtube.com/watch?v=14IKFvKiNqM) plugin addresses this problem pretty nicely allowing to update the text via double click. I'll need to investigate to see how he does it. I have limited knowledge about cocoascript as such and documentation is not all that good.
