### ISSUE TITLE
Options Panel

### ISSUE THREAD

**Issue by raulfunkie** [fuggfuggfugg/sketch-dynamic-button-3.5#8]
Hello.

It'd be nice to have like a options panel where you could set up the keyboard shortcut. I find myself using cmd+d, and everytime the plugin updates I have to manually change it.

What do you think?

**Comment by fuggfuggfugg** [comment]
I'll definitely look into it. The dev documentation is not as extensive so I'm not sure if this is possible. Have you seen this in action in some other plugin? If so let me know.

**Comment by raulfunkie** [comment]
I've seen a few that use "modals" to display certain options and settings for their plugin. None of these use it for setting up the shortcut tho.

These are a couple of plugins that use modals for their settings and whatnot. Maybe we can go from there to see if this can be implemented.

https://github.com/elliotekj/specify
https://github.com/awt2542/ViewController-for-Framer
https://github.com/aleludovici/sketch-proportional-replicator

**Comment by raulfunkie** [comment]
This is probably the code used to show a "modal" on a plugin, but I have yet to find out how does one customize it to show the shortcut and be able to change it.

(Taken from Sketch Proportional Replicator)

```
function showAlertWindow() {
        var alertWindow = COSAlertWindow.new()
        alertWindow.setMessageText('Dynamic Button Settings')

        alertWindow.addTextLabelWithValue('Custom Shortcut (Original CMD+J')
        alertWindow.addTextFieldWithValue('1') // the shortcut box should be here

        alertWindow.addButtonWithTitle('Save')
        alertWindow.addButtonWithTitle('Cancel')
        } else {
            return null
}
```

**Comment by fuggfuggfugg** [comment]
Getting input values should be easy, updating or overriding the existing keybinding is something I'm not sure if it's even possible. I've put this out to other devs http://mail.sketchplugins.com/pipermail/dev_sketchplugins.com/2016-June/003853.html

If it's pretty straightforward, I'll do it. However I just learnt that a native button feature in Sketch is not far  http://mail.sketchplugins.com/pipermail/dev_sketchplugins.com/2016-June/003851.html

PS: Thanks for your feedback and contribution. Thanks for using the plugin too.
